// Logo
var stage = new swiffy.Stage(document.getElementById('logo'),
          metrotvnews, {});
      
stage.start();
stage.setBackground(null);

// Menu Pusher
new mlPushMenu( document.getElementById( 'mp-menu' ), document.getElementById( 'trigger' ) );

// Sticky
// Generated by CoffeeScript 1.7.1
(function () {
    var reset_scroll;

	$(function () {
        return $("[data-sticky_column]").stick_in_parent({
		  parent: "[data-sticky_parent]",
		  offset_top: 65,
		  inner_scrolling:false
		});
    });

    reset_scroll = function () {
        var scroller;
        scroller = $("body,html");
        scroller.stop(true);
        if ($(window).scrollTop() !== 0) {
            scroller.animate({
                scrollTop: 0
            }, "fast");
        }
        return scroller;
    };

    window.scroll_it = function () {
        var max;
        max = $(document).height() - $(window).height();
        return reset_scroll().animate({
            scrollTop: max
        }, max * 3).delay(100).animate({
            scrollTop: 0
        }, max * 3);
    };

    window.scroll_it_wobble = function () {
        var max, third;
        max = $(document).height() - $(window).height();
        third = Math.floor(max / 3);
        return reset_scroll().animate({
            scrollTop: third * 2
        }, max * 3).delay(100).animate({
            scrollTop: third
        }, max * 3).delay(100).animate({
            scrollTop: max
        }, max * 3).delay(100).animate({
            scrollTop: 0
        }, max * 3);
    };

    $(window).on("resize", (function (_this) {
        return function (e) {
            return $(document.body).trigger("sticky_kit:recalc");
        };
    })(this));

}).call(this);

// SEARCH
(function () {
    var morphSearch = document.getElementById('morphsearch'),
            input = morphSearch.querySelector('input.morphsearch-input'),
            ctrlClose = morphSearch.querySelector('span.morphsearch-close'),
            isOpen = isAnimating = false,
            // show/hide search area
            toggleSearch = function (evt) {
                // return if open and the input gets focused
                if (evt.type.toLowerCase() === 'focus' && isOpen)
                    return false;

                var offsets = morphsearch.getBoundingClientRect();
                if (isOpen) {
                    classie.remove(morphSearch, 'open');
                     $(".morphsearch").css('min-height', '');
                     $(".morphsearch").css('overflow', 'hidden');
                    // trick to hide input text once the search overlay closes 
                    // todo: hardcoded times, should be done after transition ends
                    if (input.value !== '') {
                        setTimeout(function () {
                            classie.add(morphSearch, 'hideInput');
                           
                            setTimeout(function () {
                                classie.remove(morphSearch, 'hideInput');                                
                                input.value = '';
                            }, 300);
                        }, 500);
                    }
                    var time = 700;
                    setTimeout(function () {
                        $(".morphsearch").css('background-color', '#133593');                       
                        
                    }, time);
                    input.blur();
                }
                else {
                    var newheight = $( window ).height();
                    classie.add(morphSearch, 'open');
                    $(".morphsearch").css('background-color', '#f1f1f1');
                    $(".morphsearch.open").css('min-height', newheight);
                    var times = 1000;
                    setTimeout(function () {
                        $(".morphsearch.open").css('overflow', 'auto');                    
                        
                    }, times);
                    
                }
                isOpen = !isOpen;
            };

    // events
    input.addEventListener('focus', toggleSearch);
    ctrlClose.addEventListener('click', toggleSearch);
    // esc key closes search overlay
    // keyboard navigation events
    document.addEventListener('keydown', function (ev) {
        var keyCode = ev.keyCode || ev.which;
        if (keyCode === 27 && isOpen) {
            toggleSearch(ev);
        }
    });


    /***** for demo purposes only: don't allow to submit the form
    morphSearch.querySelector('button[type="submit"]').addEventListener('click', function (ev) {
        ev.preventDefault();
    }); *****/
})();

// MENU
$(".menu .option li").mouseover(function (event) {
    $(this).addClass("current");
    $(this).siblings().removeClass("current");
    var tab = $(this).attr("title");
    $(".submenu ul").not(tab).css("display", "none");
    $(tab).fadeIn();
	$(".kanalmenu").css('zIndex', '0');  
});

$(".top").mouseleave(function (event) {
    $(".kanalmenu").css('zIndex', '0');  
	$(".st-1").css('display', 'block');  

});

$(".stg").hover(function (event) {
    $(".kanalmenu").css('zIndex', '1');  
});

// TAB MOST
$(".most-menu a").click(function (event) {
    event.preventDefault();
    $(this).parent().addClass("current");
    $(this).parent().siblings().removeClass("current");
    var tab = $(this).attr("href");
    $(".most-content").not(tab).css("display", "none");
    $(tab).fadeIn();
});

// TAB VIDEO
$(".video-menu a").click(function (event) {
    event.preventDefault();
    $(this).parent().addClass("current");
    $(this).parent().siblings().removeClass("current");
    var tab = $(this).attr("href");
    $(".video-content").not(tab).css("display", "none");
    $(tab).fadeIn();
});

// Untuk scroll
$(window).load(function(){
	$(".footer-scroll").mCustomScrollbar({
		autoHideScrollbar:true,
		theme:"minimal"
	});
});

// GALERI FOTO
var slideCount = $('#galeri ul li').length;
var slideWidth = $('#galeri ul li').width();
var slideHeight = $('#galeri ul li').height();
var sliderUlWidth = slideCount * slideWidth;

$('#galeri').css({width: slideWidth, height: slideHeight});

$('#galeri ul').css({width: sliderUlWidth, marginLeft: -slideWidth});

$('#galeri ul li:last-child').prependTo('#galeri ul');

function moveLeft() {
    $('#galeri ul').animate({
        left: +slideWidth
    }, 200, function () {
        $('#galeri ul li:last-child').prependTo('#galeri ul');
        $('#galeri ul').css('left', '');
    });
}
;

function moveRight() {
    $('#galeri ul').animate({
        left: -slideWidth
    }, 200, function () {
        $('#galeri ul li:first-child').appendTo('#galeri ul');
        $('#galeri ul').css('left', '');
    });
}
;

$('.control_prev').click(function () {
    moveLeft();
});

$('.control_next').click(function () {
    moveRight();
});

// Footer Show Hide When Scrolling or Not!
$(function () {

    $(window).scroll(function () {
        if ($(".sitemap").css('display') === 'block')
        {
            $(".footer").fadeIn();
        } else {
            $(".footer").fadeOut();
        }
        clearTimeout($.data(this, "scrollCheck"));
        $.data(this, "scrollCheck", setTimeout(function () {
            $(".footer").fadeIn();
        }, 1500));

    });

});

// Share
$(document).on('click', '.share .label', function() {
	$( this ).toggleClass( "act" );
	$( this ).next().toggleClass( "open" );
});

// Footer
$(".openfooter").click(function () {
    $(".sitemap").toggle("slow");
    $(".copyright").toggle("slow");
    $('.openfooter .fa').toggleClass("fa-angle-double-up  fa-angle-double-down");
});

//live streaming newsticker
$.fn.textWidth = function(text, font) {
    if (!$.fn.textWidth.fakeEl) $.fn.textWidth.fakeEl = $('<span>').hide().appendTo(document.body);
    $.fn.textWidth.fakeEl.text(text || this.val() || this.text()).css('font', font || this.css('font'));
    return $.fn.textWidth.fakeEl.width();
};
var note = $('.word p').textWidth();
$('.word p').css('width', note );
